name: Deploy to Vercel Preview
env : 
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}

on:
  workflow_dispatch:
  push:
    branches:
      - manage-forms


jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v4
            - name: install Vercel CLI
              run: npm install --global vercel@latest
            - name: pull Vercel environment information
              run: Vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: build project artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            # - name: deploy project artifacts to Vercel
            #   run: vercel deploy --prebuilt  --token=${{ secrets.VERCEL_TOKEN }}
            - name: assign beta domain
              run:
                vercel deploy -- prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
                vercel alias --scope ${{ secrets.VERCEL_TEAM_ID }} --token ${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` linkfree-preview.vercel.app