name: Deploy to Vercel
env : 
    VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      # this will deploy data files only  when no release is created
      - main
    paths:
      - "data/**"


jobs:
    deploy:
      if: github.repository == 'Linkfree'
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v4
            - name: install Vercel CLI
              run: npm install --global vercel@latest
            - name: pull Vercel environment information
              run: Vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: build project artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: deploy project artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} > doamin.txt